name: app
type: 'php:8.4'

disk: 2048

build:
  flavor: composer

web:
  locations:
    '/':
      root: 'public'
      index: ['index.php']
      passthru: '/index.php'

mounts:
  'storage':
    source: local
    source_path: storage
  'web/uploads':
    source: local
    source_path: uploads

relationships:
  postgresql: 'postgresql:postgresql'

hooks:
  build: |
    echo "Build terminé"
  deploy: |
    php artisan migrate --force
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
