name: app
type: php:8.0
dependencies:
  php:
    composer/composer: '^2'
runtime:
  extensions:
    - redis
build:
  flavor: composer
variables:
  env:
    N_PREFIX: /app/.global
hooks:
  deploy: |
    set -e
    php artisan optimize:clear
    php artisan optimize
    php artisan view:cache
    php artisan migrate --force
relationships:
  database: "db:mysql"
  rediscache: "cache:redis"
  redissession: "cache:redis"
disk: 2048
mounts:
  "storage/app/public":
    source: local
    source_path: "public"
  "storage/framework/views":
    source: local
    source_path: "views"
  "storage/framework/sessions":
    source: local
    source_path: "sessions"
  "storage/framework/cache":
    source: local
    source_path: "cache"
  "storage/logs":
    source: local
    source_path: "logs"
  "bootstrap/cache":
    source: local
    source_path: "cache"
  "/.config":
    source: local
    source_path: "config"
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
    "/storage":
      root: "storage/app/public"
      scripts: false
workers:
  queue:
    size: S
    commands:
      start: |
        php artisan queue:work --max-time=3600
    disk: 256
  scheduler:
    size: S
    commands:
      start: php artisan schedule:work
    disk: 256
