name: app
type: 'php:8.2'
build:
  flavor: composer
web:
  locations:
    '/':
      root: 'public'
      index: 'index.php'
      passthru: '/index.php'
relationships:
  database: 'mysql:mysql'
hooks:
  build: |
    composer install --no-dev --optimize-autoloader
  deploy: |
    php artisan migrate --force
    php artisan config:cache
